# Site/SEO settings
email: highbrighten@gmail.com
baseurl: "/blog"
permalink: /:year/:month/:title
google_analytics: 

name: mattjo
title: 그럼에도 불구하고
description: 생각을 엮습니다
url: https://mattjo.net
twitter_username: mattjgo
default_img: /assets/images/profile.jpg

# Contact settings
formcarry: https://formcarry.com/s/k3RuRf1t-Sv

# Disqus settings
disqus: mattjogo

# Author settings
author:
  - name: Matthew Jo
    bio: 한 줄로 나 자신을 소개하는건 어찌 매번 어려울까요
    url: https://mattjo.net

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
